storybook/src/form-elements/FormLayout.mdx
storybook/src/form-elements/FormLayout.stories.tsx

* Module: storybook
Incorrect import of FormLayout component.
Closes #5

#5 Fix FormLayout imports

---

libs/core/src/Tabs.tsx

When using tabs, the focus always shifts to the component when clicking on a certain tab.
This functionality should only occur when scrollable tabs are enabled (most often on mobile devices), not in other use cases.
Closes #11

#11 Fix always autofocus on Tabs

---

libs/form-elements/src/Field.tsx
libs/form-elements/src/Input.tsx
libs/selectors/src/Autocomplete.tsx
storybook/src/base-documentation/Introduction.stories.mdx

When using Autocomplete component with tags error message appears above the tags.
Closes #9

#9 Fix Autocomplete error message displaying above tags

---

libs/icons/src/index.tsx

* Module: @tiller-ds/icons
Change phosphor-icons import path.
Closes #26 

#26 Fix Icons Import

---

package.json
storybook/.storybook/preview.js
storybook/playroom.config.js

* Module: project 
Setup of playroom and tailwind for build was incorrect. This PR fixes it
Configuration url for playroom was updated, loader for icons css was added.
#20 

#20 Fixed playroom and tailwind configuration

---

libs/core/src/ProgressBar.tsx
libs/theme/src/defaultTheme.tsx

* Module: menu
Progress Bar component behaves strange when a lot of steps are defined, margins and padding are off and need to
be adjusted.
Closes #15

#15 Fix Progress Bar step margin

---

.prettierrc.js
libs/menu/src/SidebarNavigation.tsx
libs/theme/src/defaultTheme.tsx

* Tiller version: 1.1.0
* Module: menu
Move Sidebar Navigation classes which make sense to be modifiable through tokens to defaultTheme.
Closes #46

#46 Move Sidebar Navigation classes to tokens

---

libs/form-elements/src/FormLayout.tsx
libs/theme/src/defaultTheme.tsx
storybook/src/form-elements/FormLayout.stories.tsx
storybook/src/menu/SidebarNavigation.mdx

* Module: storybook, form-elements
Update the SidebarNavigation docs, move FormLayout classes to the defaultTheme, fix placement of the FormLayout in storybook.
Closes #58 

#58 Move FormLayout classNames to defaultTheme

---

libs/form-elements/src/Input.tsx

On the contained tags variant of Autocomplete some tags (on the right side of the container) cannot be removed because a div is on top of those elements.
Closes #53

#53 Autocomplete - fix inability to remove contained tags

---

libs/formik-elements/src/AutocompleteField.tsx
libs/selectors/src/Autocomplete.tsx

* Module: selectors, formik-elements
- onReset now receives one argument which is a boolean and indicates whether or not multiple selection is enabled
- If allowMultiple is on: 
- onReset(true) -> value becomes **[]**
- If allowMultiple is off:
- onReset (false)-> value becomes **null**
Closes #55 
- Enhancement (semi-breaking change which enhances existing functionality)

#55 Autocomplete(Field) - improve onReset behavior

---

libs/menu/src/SidebarNavigation.tsx

* Module: menu
When passing 'icon' prop to an expandable Sidebar Navigation item the icon is not visible next to the item title.
Icon should be visible regardless of the 'isExpandable' prop status.
Closes #67

#67 Fix invisible icon on SidebarNavigation expandable item 

---

libs/selectors/src/Autocomplete.tsx

Selecting an item when `allowMultiple` is enabled on Autoomplete results in closing of the menu and doesn't select
the desired item. 
The issue occurs because `highlightedOption` updates after `checkItem` function, hence the function doesn't actually check the item.
Closes #75

#75 Fix Autocomplete multiple item selection on mobile

---

libs/alert/package.json
libs/core/package.json
libs/data-display/package.json
libs/date/package.json
libs/dev/package.json
libs/form-elements-advanced/package.json
libs/form-elements/package.json
libs/formik-elements/package.json
libs/icons/package.json
libs/intl/package.json
libs/menu/package.json
libs/patterns/package.json
libs/selectors/package.json
libs/theme/package.json
libs/upload/package.json
libs/util/package.json

Add description property to `package.json` for every module.
Closes #81
- Visibility improvement

#81 Add description to modules

---

libs/formik-elements/src/InputField.tsx
storybook/src/formik-elements/InputField.stories.tsx

* Tiller version: 1.4.0
* Module: formik-elements
Add custom text transform prop. 
Add valueTransform prop which is function or a string that determines how the input value should be transformed when the user types into the input field. In case it's a function, it will be called every time the input value changes. The function can then modify the value as needed and return the modified value.
Closes #97 

#97 Add valueTransform prop to InputField

---

libs/date/src/DateInput.tsx
libs/date/src/DateRangeInput.tsx
libs/date/src/DateTimeInput.tsx

* Tiller version: 1.4.0
* Module: date
When selecting a date from the picker on Date Input and Date Time Input components the date mask dislocates when
focusing on an input. Manual entry doesn't cause this effect and works normally. 
Closes #94

#94 Fix dislocated mask on Date/Time Inputs

---

libs/intl/src/intlDictionary.js
libs/selectors/src/Autocomplete.tsx
libs/theme/src/defaultTheme.tsx
storybook/src/formik-elements/AutocompleteField.mdx
storybook/src/formik-elements/AutocompleteField.stories.tsx
storybook/src/selectors/Autocomplete.mdx
storybook/src/selectors/Autocomplete.stories.tsx

- renamed prop onAddCustomTag to getCustomItem
- added onAddCustomItem prop for handling new items persistence inside the component
- adding new custom items is now available for all Autocomplete variants
Closes #69
- Enhancement (semi-breaking change which enhances existing functionality)
- Docs improvement

#69 Extend custom items capability to all Autocomplete variants

---

libs/date/src/DateInput.tsx
libs/date/src/DatePicker.tsx
libs/date/src/DateRangeInput.tsx
libs/date/src/DateTimeInput.tsx
libs/date/src/TimeInput.tsx
libs/theme/src/defaultTheme.tsx
storybook/src/date/DateInput.stories.tsx
storybook/src/date/DateRangeInput.stories.tsx
storybook/src/date/DateTimeInput.stories.tsx
storybook/src/formik-elements/DateInputField.stories.tsx
storybook/src/formik-elements/DateRangeInputField.stories.tsx
storybook/src/formik-elements/DateTimeInputField.stories.tsx

* Tiller version: 1.5.0
* Module: date
- added _highlightToday_ prop to: `DateInput`, `DateRangeInput`, `DateTimeInput`
- added `WithHighlightedCurrentDate` stories to inputs to showcase the behaviour
- added new `currentDate` token which includes styling for today's date  (`DatePicker.Button.currentDate`)
Closes #91 
- Visual improvements (non-breaking change which enhances existing functionality)

#91 Add possibility of highlighting current date to date inputs

---

libs/formik-elements/src/AutocompleteField.tsx
libs/selectors/src/Autocomplete.tsx
storybook/src/formik-elements/AutocompleteField.stories.tsx
storybook/src/selectors/Autocomplete.stories.tsx

* Tiller version: 1.5.0
* Module: form-elements, formik-elements
Add custom text transform prop.
Add valueTransform prop which is function or a string that determines how the input value should be transformed when the user types into the input field. In case it's a function, it will be called every time the input value changes. The function can then modify the value as needed and return the modified value.
Closes #104 
- Docs change

#104 Add valueTransform prop to Autocomplete

---

storybook/src/menu/AppPicker.stories.tsx

* Tiller version: 1.5.0
* Module: storybook
When accessing the AppPicker component in Storybook, the component is invisible inside Storybook. 
The docs and code are displayed properly, but the visual representation is missing.
Closes #106

#106 Fix AppPicker not visible inside Storybook

---

libs/formik-elements/src/AutocompleteField.tsx

* Tiller version: 1.6.0
Setting a new value through Formik helpers for `AutocompleteField` doesn't work as expected when _sendOptionValue_ is set to `false`. In this case, the value correctly changes in the end, but gets set incorrectly before that by setting the value as if the _sendOptionValue_ prop is disabled. This behaviour should be consistent in its results when changing the value in order to correctly track the field values.
Closes #110

#110 Improve AutocompleteField value change consistency when sendOptionValue is disabled

---

libs/date/src/DateInput.tsx
libs/date/src/DateTimeInput.tsx
libs/date/src/TimeInput.tsx

* Tiller version: 1.6.0
* Module: date
The _onBlur_ prop for `DateInput` and `TimeInput` is not registering blur events. 
The _onBlur_ prop for `DateTimeInput` is executed twice instead of once.
Closes #113

#113 Fix inconsistent onBlur for Date, DateTime and Time inputs

---

libs/core/src/Tabs.tsx
storybook/src/core/Tabs.mdx
storybook/src/core/Tabs.stories.tsx

v1.6.1
* Module:
tiller/core
Added index and onTabChange props to Tab for grater control
Added index and onTabChange props which combined enable full control over Reach Tabs sub component
ref: https://github.com/croz-ltd/tiller/issues/119
- Docs change
- [ x ] I have read the project's **CONTRIBUTING** document
- [ x ] I have checked my code with the project's static analysis tooling
- [ x ] I have formatted my code with the project's Prettier code-style configuration
- [ x ] I have checked my code for misspellings
- [ x ] I have organized my changes in easy-to-follow commits
- [ x ] My change requires a change to the documentation
- [ x ] I have updated the documentation accordingly
- [ x ] I have added a …

feature: #119 Greater control over Tab

---

libs/date/src/utils.tsx

* Module: date
Date mask sometimes behaves strange when clicking away from any date input components.
This is because of the logic behind determining the allowed month input number returning a false allowed number in a small number of use cases. In these cases the mask falls back to the range of numbers 0-2, thus removing the numbers which did not pass this test and glitching the date mask.
List of components: DateInput, DateRangeInput, DateTimeInput
Closes #118

#118 Fix logic for determining month input on date mask

---

libs/date/src/DateInput.tsx
libs/date/src/DateRangeInput.tsx
libs/date/src/DateTimeInput.tsx
libs/date/src/TimeInput.tsx
libs/formik-elements/src/TimeInputField.tsx

* Module: date
Detection of `onBlur` events occurs too early, which is especially noticable when using a form with validation which can trigger on date inputs. This can disrupt the UX experience on modals, for example, where the whole form shifts for a split second if this occurs (validation message shifts the components).
Closes #117

#117 Fix onBlur detection for date(time) input components

---

storybook/src/base-documentation/ThemingAndCustomization.stories.mdx

* Module: docs
The link to Figma token set presented in the Theming and Customization page of the Storybook's [docs](https://croz-ltd.github.io/tiller/?path=/docs/theming-and-customization--page#importing-the-token-set) is not functional, which makes retrieving the token set impossible for end users.
Closes #123

#123 Fix Figma tokens download link

---

libs/date/src/DateInput.tsx
libs/date/src/DateTimeInput.tsx

* Module: form-elements, formik-elements
Resetting the value for `DateInputField` and `DateTimeInputField` through Formik helpers resets the component state (field value), but not the visual representation of the value inside the field. 
The component should be consistent in its behaviour, detect when a value is changed externally and set its internal state accordingly if the field is NOT the currently focused element in the window.
Closes #137

#137 Fix external value change consistency for DateInputField and DateTimeInputField

---

libs/menu/src/SidebarNavigation.tsx

* Module: menu
`SidebarNavigation` and `TopNavigation` components are inconsistent in their checks for active item state:
- `SidebarNavigation` strictly checks whether the pathname **is equal** to `to` prop
- `TopNavigation` checks whether the pathname **starts with** `to` prop
The check behaviour should be consistent between these 2 components.
Closes #131

#131 Fix active state misalignment between SidebarNavigation and TopNavigation

---

libs/upload/src/DragZone.tsx
libs/upload/src/UploadButton.tsx
libs/upload/src/UploadyWrapper.tsx

* Tiller version: 1.7.1
* Module: upload
Exposed `withCredentials` on all upload components
Closes #145 

#145 Add withCredentials to upload components

---

libs/menu/src/Dropdown.tsx

* Module: core
Fixed warning rendered in console when using a DropdownMenu component.
Closes #152

#152 Fix validateDOMNesting warning when rendering Dropdown component

---

libs/alert/src/Modal.tsx

* Module: core
Fixed a `DialogContent` warning generated in the console when rendering a Modal component by adding an `aria-label` prop to `DialogContent`.
Closes #163

#163 Fix `Modal`'s `DialogContent` warning

---

libs/form-elements/src/Input.tsx

Fixed a `ForwardRef` warning appearing in the console when rendering components that use the `Input` component on render.
Closes #165 

#165 Fix `ForwardRef` warning when using Input with other components

---

libs/form-elements/src/Input.tsx
libs/form-elements/src/MaskedInput.tsx
libs/menu/src/DropdownMenu.tsx

* Module: menu
Fixed `visibleItemCount` prop consistency when changing values for `DropdownMenu` component.
Closes #160 

#160 Fix `visibleItemCount` consistency for `DropdownMenu` component

---

storybook/src/form-elements/NumberInput.mdx
storybook/src/formik-elements/NumberInputField.mdx

* Module: formik-elements
All props available to NumberInputField are listed in Storybook docs.
Closes #150 
- Docs change

#150 - NumberInputField Storybook documentation missing props

---

libs/data-display/src/DataTable.tsx
storybook/src/data-display/DataTable.stories.tsx

Add an option of displaying a custom content when the table is empty.
Closes #133 

#133 - Empty DataTable state custom message or content

---

libs/theme/src/defaultTheme.tsx
libs/upload/src/DragZone.tsx
libs/upload/src/index.tsx
storybook/src/formik-elements/DragZoneField.stories.tsx
storybook/src/upload/DragZone.stories.tsx

* Module: upload
Added `loader` prop to `DragZone` component which defaults to a spinner and percentage indicators when uploading file(s).
Updated stories to show different variations of using the `loader` prop, including using a custom loader or no loader at all.
Closes #178 
- Docs change

#178 Display DragZone upload progress

---

libs/data-display/src/index.tsx
libs/data-display/src/useSortableDataTable.tsx
storybook/src/data-display/DataTable.mdx
storybook/src/data-display/DataTable.stories.tsx

DataTable sorting made possible by providing a default sorting hook to ease and reduce development process.
Closes #149 
- Docs change

#149 - DataTable sorting - hook proposal

---

libs/data-display/src/DataTable.tsx
storybook/src/data-display/DataTable.mdx
storybook/src/data-display/DataTable.stories.tsx

Enable multi-column sorting functionality in the DataTable component.
Closes #182 
- Docs change

#182 - Enable Multi-column sorting in DataTable

---

libs/menu/src/DropdownMenu.tsx
storybook/src/menu/DropdownMenu.stories.tsx

* Module: menu
Fixed the issue of incorrect child detection in the DropdownMenu component by implementing a filtering mechanism to exclude conditionally rendered items that should not appear in the children array. 
Fixed the issue of incorrect menu height when `visibleItemCount` prop is set to a value larger than the length of the children array.
Added a story to showcase the usage of `DropdownMenu` with `visibleItemCount` enabled.
Closes #191 

#191 Fix and improve children handling on DropdownMenu

---

libs/selectors/src/Select.tsx

Fixed unintentional form submission when clicking a clear button on `Select` component.
Closes #196 

#196 Fix clear button accidentally submitting a form on Select

---

libs/date/src/DateRangeInput.tsx

Fixed redundant focusing of `DateRangeInput(Field)` component when shifting away from the component after selection of dates from the date picker.
Closes #198 

#198 Fix redundant `DateRangeInput(Field)` focus

---

libs/form-elements-advanced/src/RichTextEditor.tsx

* Module: form-elements-advanced
Changed `htmlObject.getElementsByTagName("p")` to `Array.from(htmlObject.querySelectorAll("p"))` because the return of the `getElementsByTagName()` function is not iterable, which causes `semantic error TS2569: Type 'HTMLCollectionOf<HTMLParagraphElement>' is not an array type or a string type.`
Closes #204 

#204 RichTextEditor semantic error TS2569

---

libs/form-elements/src/NumberInput.tsx
storybook/src/form-elements/NumberInput.mdx
storybook/src/formik-elements/NumberInputField.mdx

* Module: form-elements, formik-elements
Added better checking for `decimalSeparator` and `thousandSeparator` definition on `NumberInput(Field)` component and allowed empty string value ("") for `decimalSeparator` prop.
Added a check for the validity of `thousandSeparator` prop and implemented an error message if an empy string ("") is defined for this prop.
Closes #159 

#159 Add empty string support as `thousandSeparator` for NumberInput(Field)

---

libs/selectors/src/Autocomplete.tsx
libs/selectors/src/Select.tsx

Fixed non-existent `name` attribute on `Select` component which allows the `useScrollToError` hook to catch the element for error detection.
Fixed `Autocomplete` (multiple selection) input styling from `hidden` to `w-0 h-0 `so that the element exists and can be found by the hook.
Closes #193 

#193 Fix Select and Autocomplete (multiple selection) input references

---

package.json

The following command: `"build": "nx run-many --target=build --projects=alert,core,data-display,date,dev,form-elements,form-elements-advanced,formik-elements,icons,intl,menu,patterns,selectors,theme,upload,util --paralel --prod && node scripts/refactor-dependecies",` has a typo, the flag `--parallel` was spelled as `--paralel` which would cause the code to not run in parallel.
Closes #212 

#212 Optimizing build time

---

libs/data-display/src/DataTable.tsx
storybook/src/data-display/DataTable.stories.tsx

Added `onClick` prop to `DataTable` component which takes the clicked row value as a parameter (similar to `onDoubleClick` function).
Added a story to demonstrate newly added `onClick` functionality.
Closes #201 

#201 Add onClick prop and functionality to DataTable

---

libs/upload/src/DragZone.tsx
libs/util/src/index.tsx
libs/util/src/usePrevious.tsx

* Tiller version: 1.9.0
Fixed build errors and import errors for `usePrevious` by correctly exporting the hook from the `util` module.
Closes #224 

#224 Fix `usePrevious` hook import/export issue

---

libs/core/src/Breadcrumbs.tsx

1.12.0
* Module:
core
Fixed a bug when icon is rendered between non-rendered elements of Breadcrumbs component.
Added check if child is undefined before rendering breadcrumb icon and breadcrumb child.
https://github.com/croz-ltd/tiller/issues/241

#241 Fix bug when Breadcrumbs icon is rendered between non-rendered elements

---

libs/theme/src/defaultTheme.tsx

* Module: theme
Fixed conflicting class names applied to the current date in date picker (rendered for every date input component) if `highlightToday` prop is enabled and current date is selected.
When enabling `highlightToday` prop, the look of the highlighted day is strange, with conflicting class names applied at the same time: `text-primary-contrast` and `text-primary-dark`. This causes the date to have the dark class name applied sometimes (depending on which class name is compiled first), resulting in a visually unappealing result.
#254 

#254 Fix date picker current date's conflicting text class names

---

libs/menu/src/DropdownMenu.tsx

* Module: menu
Fixed logic for registering styling for `DropdownMenu`'s `openExpanderIcon` and `closeExpanderIcon` props by prioritizing defined props directly from the `<Icon .../>` component over defaults.
Logic for styling icons follows this flow:  
- if `open/closeExpanderIcon` is defined without any props, defaults are set 
- if `open/closeExpanderIcon` is defined with some props, those props override defaults, while other props resort to defined defaults
#251 

#251 Fix DropdownMenu not registering icon props properly

---

libs/theme/src/styles/tiller.css

* Module: core
Fixed `@reach/tabs` warning appearing in the console when rendering `Tabs` component by supressing the styles warning in the main styles file `tiller.css`.
#261

#261 Fix `@reach/tabs` warning in the console

---

libs/core/src/Badge.tsx
libs/core/src/Button.tsx
libs/form-elements/src/Input.tsx
libs/form-elements/src/NumberInput.tsx
libs/form-elements/src/Textarea.tsx
libs/selectors/src/Autocomplete.tsx
libs/selectors/src/Select.tsx

1.13.0
Added name based id generation on `Autocomplete` and `Select` components by assigning the value of `input-${name}` to the respective `id` props.
https://github.com/croz-ltd/tiller/issues/253

#253 Add name-based id generation for Autocomplete and Select

---

libs/data-display/src/DataTable.tsx
libs/data-display/src/useSortableDataTable.tsx
storybook/src/data-display/DataTable.stories.tsx

Added possibility of retaining initial sort defined by `defaultSortBy` prop when sorting `DataTable`'s columns via header arrows.
New prop has been added for retaining initial sort configuration:
- `retainDefaultSortBy`
#236 

#236 DataTable - add `retainDefaultSortBy` prop for preserving default sorting

---

libs/data-display/src/DataTable.tsx
storybook/src/base-documentation/ReleaseNotes.stories.mdx

* Tiller version: 1.14.0
Fixed `children.map` error appearing when rendering the `DataTable` component with only one column present in a row.
#266 

#266 Fix DataTable crashing if number of children in a row is 1

---

libs/data-display/src/DataTable.tsx
storybook/src/base-documentation/ReleaseNotes.stories.mdx

* Tiller version: 1.14.1
Fixed `maximum render depth` error appearing when rendering the `DataTable` component with primary/secondary columns.
#268

#268 Fix `DataTable` primary/secondary row rendering loop

---

libs/form-elements-advanced/src/RichTextEditor.tsx

* Tiller version: 1.14.2
* Module: form-elements-advanced
Fixed duplication of `initialHtml` prop when initially rendering `RichTextEditor` component with `React.StrictMode` enabled (on dev environments).
#274 

#274 Fix `initialHtml` duplicated on `RichTextEditor` initial render

---

libs/selectors/src/Autocomplete.tsx
libs/theme/src/defaultTheme.tsx

* Tiller version: 1.14.2
Fixed visual inconsistencies between disabled input components by adding a joint class name `bg-slate-100` to input and select components for uniform disabled look.
#273

#273 Fix visual inconsistencies between disabled input components

---

libs/menu/src/SidebarNavigation.tsx
libs/menu/src/TopNavigation.tsx

* Tiller version: 1.15.1
* Module: menu
Expanded `title` prop on `TopNavigation` and `SidebarNavigation` components by changing its type:
- Old type - `string`
- New type - `React.ReactNode`
#287 

#287 Extend type of title prop on TopNavigation and SidebarNavigation

---

libs/alert/src/Notification.tsx
libs/alert/src/NotificationProvider.tsx
libs/icons/src/Icon.tsx
libs/icons/src/iconConfig.tsx
libs/theme/src/defaultTheme.tsx
libs/theme/src/index.tsx
libs/theme/src/useIcon.tsx
storybook/src/alert/Notification.mdx
storybook/src/alert/Notification.stories.tsx
storybook/src/alert/NotificationProvider.stories.tsx

1.15.1
* Module: alert
Expanded `Notification`'s customization capabilities by adding additional props:
- `type` - changes the default look and feel of the notification (`success`/`info`/`danger`/`warning`)
- `disableAccent` - disables the accent background color that follows the `type` prop's look and feel
- `iconProps` - enables modifying `size`, `className` and `variant` props of default main and dismiss icons
Other improvements:
- improved tokens by moving all remaining classes into tokens
- added `success`, `info`, `danger` and `warning` default icons into default icon config
- reduced the size of `Notification`'s default dismiss button to a more appropriate size
#283 
- New feature …

#283 Expand `Notification`'s customization capabilities

---

libs/formik-elements/src/SelectField.tsx
libs/selectors/src/Select.tsx
storybook/src/formik-elements/SelectField.stories.tsx
storybook/src/formik-elements/TreeSelectField.stories.tsx
storybook/src/selectors/Select.stories.tsx

* Tiller version: 1.15.1
Fixed `Select(Field)`'s broken functionality when 0 is provided as a value (`Select` and `SelectField`) or when 0 is the return value of `getOptionValue` prop (`SelectField`).
#291 

#291 Fix `Select(Field)` not working with 0 value

---

libs/intl/src/IntlProvider.tsx

* Tiller version: 1.17.0
* Module: intl
Adds support for defaultRichTextElements prop to IntlProvider, allowing consumers to customize how rich text elements are rendered in translated messages.
#304 

#304 - Forward defaultRichTextElements to react-intl context
