croz-ltd/tiller

- .github/workflows/build.yml
- README.md
- package.json
Change URL-s, update package.json.
#4 
- Docs change
> #4 Add Business Materials

- README.md
Change Storybook URL
#4 
- Docs change
> #4 Change Storybook URL

- README.md
Correct cover image URL, beautify links for Figma UI Kit and Storybook. Add description for Storybook.
#4 
- Docs change
> #4 Correct cover image URL, beautify links

- storybook/.storybook/main.js
- storybook/playroom.config.js
- storybook/src/base-documentation/Introduction.stories.mdx
- storybook/src/core/Badge.mdx
- storybook/src/core/Button.stories.tsx
- storybook/src/core/ButtonGroups.stories.tsx
- storybook/src/core/Pagination.mdx
- storybook/src/date/DateInput.mdx
- storybook/src/dev/FetchDebug.mdx
- storybook/src/form-elements-advanced/RichTextEditor.mdx
- storybook/src/form-elements-advanced/RichTextEditor.stories.tsx
- storybook/src/form-elements/CheckboxGroup.mdx
- storybook/src/form-elements/Input.mdx
- storybook/src/form-elements/RadioGroup.mdx
- storybook/src/formik-elements/CheckboxGroupField.mdx
- storybook/src/formik-elements/DataTableField.mdx
- storybook/src/formik-elements/DateRangeInputField.mdx
- storybook/src/formik-elements/FieldError.mdx
- storybook/src/formik-elements/FieldError.stories.tsx
- storybook/src/formik-elements/InputField.mdx
- storybook/src/formik-elements/SelectField.mdx
- storybook/src/formik-elements/TreeSelectField.stories.tsx
- storybook/src/menu/DropdownMenu.mdx
- storybook/src/menu/DropdownMenu.stories.tsx
- storybook/src/selectors/Autocomplete.mdx
- storybook/src/selectors/PageResizer.mdx
- storybook/src/utils/data.tsx
* Module: storybook
- improve docs for various components 
- create docs for FieldError and RichTextEditor
- improve code output for factories
- fix Playroom base url
Closes #20 
- docs corrections
- stories' code improvement
- fix Playroom
> #20 Storybook and Playroom corrections

- CONTRIBUTING.md
- README.md
Add version info in README.md and branching policy to CONTRIBUTING.md.
#4 
- Docs change
> #4 Update CONTRIBUTING.md & README.md

- storybook/src/base-documentation/Installation.stories.mdx
Fix template in cra command in Installation.stories.mdx
#4 
- Docs change
> #4 Docs Fix CRA command

- storybook/.storybook/tillerStorybookTheme.js
Update FigmaURL on storybook tiller logo
#4 
- Docs change
- [] I have updated the documentation accordingly
> #4 Change Figma URL on brandURL

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Added Changelog for v1.0.2
Closes #25 
- Docs change
> #25 v1.0.2 Changelog

- package.json
- scripts/refactor-dependecies.js
Improvement of the script refactor-dependencies to add a repository to each package.json, as well as to add a readme file with modified package names to each lib.
Closes #30 
- Refactoring
> #30 Draft: Improve refactor-dependecies script for build

- storybook/.playroom/frameComponent.js
- storybook/.playroom/snippets.js
- storybook/playroom.config.js
Fix Playroom Snippets
Closes #33 
> #33 Fix Playroom Snippets

- libs/core/src/PageHeading.tsx
- libs/core/src/Typography.tsx
- libs/form-elements/src/FormLayout.tsx
- libs/form-elements/src/Toggle.tsx
- libs/formik-elements/src/PasswordInputField.tsx
- libs/theme/src/defaultTheme.tsx
- storybook/src/formik-elements/SelectField.mdx
- storybook/src/intl/Intl.mdx
- storybook/src/menu/SidebarNavigation.mdx
- storybook/src/menu/TopNavigation.mdx
- storybook/src/patterns/Login.mdx
* Module: core, form-elements, formik-elements, intl, theme, menu, patterns
- update docs, fix classNames and styles
Closes #32 
- Docs change
> #32 Various Component Improvements

- storybook/.storybook/preview.js
* Module: storybook
Icons import in components' preview on Storybook is wrong and causes inconsistent display of icons.
Sometimes the icons are displayed, but after refresh they disappear.
Closes #38
> #38 Fix inconsistent icons display in Storybook

- libs/menu/src/DropdownMenu.tsx
- libs/menu/src/TopNavigation.tsx
- libs/theme/src/defaultTheme.tsx
- storybook/.playroom/snippets.js
- storybook/src/menu/TopNavigation.stories.tsx
* Module: menu
On small screens Top Navigation component doesn't behave correctly. The goal is to make it as fluid as Sidebar Navigation and
create consistency between two components by adding the topRightAction prop which will make the usage of these two components similar.
Closes #36
> #36 Improve Top Navigation Responsiveness

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Added Changelog for v1.1.0
Closes #42 
- Docs change
> #42 v1.1.0 Changelog

- libs/formik-elements/src/PasswordInputField.tsx
* Module: build
Build fails because of a semantic error in Password Input Field component.
Closes #40
> #40 Fix build

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Added Changelog for v1.3.0
Closes #60
- Docs change
> #60 v1.3.0 Changelog

- libs/selectors/src/Select.tsx
Selecting an item on any variant of Select component results in an infinite loop which freezes the entire application.
Closes #71
> #71 Fix freeze when selecting an item on Select

- libs/selectors/src/Select.tsx
Fix non-responsive Select component when clicking on it.
Closes #79
- Bug fixes
> #79 Fix Select menu not opening

- libs/form-elements/src/Field.tsx
* Module: @tiller-ds/formik-elements
Node: 18.10.0
Yarn: 3.2.1
Added additional check to see if error message that comes from Formik is actually a string or React element.
Closes #77
> #77 Added additional check for error message type

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Added Changelog for v1.3.1
Closes #85 
> #85 v1.3.1 Changelog

- libs/core/src/ProgressBar.tsx
* Module: core
Add `separator` prop to Progress Bar component in order to allow users to use their custom separator svg icons 
instead of the default one.
Closes #80
- Visual improvements (non-breaking change which enhances existing functionality)
> #80 Add custom separator prop to Progress Bar

- libs/theme/src/preset.ts
- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.3.1
Added Changelog for v1.4.0
Closes #89 
- Documentation update
> #89 v1.4.0 Changelog

- libs/alert/src/Alert.tsx
- libs/theme/src/defaultTheme.tsx
- storybook/src/alert/Alert.stories.tsx
* Tiller version: 1.4.0
* Module: alert
Add an icon to alerts, as this can enhance the user experience and improve the effectiveness of the alerts.
Closes #95 
> #95 Add Icon prop to Alert

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.4.0
Added Changelog for v1.5.0
Closes #100 
- Docs change
> v1.5.0 Changelog

- libs/menu/src/NavigationContextProvider.tsx
- libs/menu/src/SidebarNavigation.tsx
- libs/menu/src/TopNavigation.tsx
- libs/menu/src/index.tsx
- libs/theme/src/defaultTheme.tsx
* Module: menu
Top Navigation and Sidebar Navigation's dropdown components are being opened/closed on every click. 
Deeper context passing and communication between subcomponents is required in order to correctly detect wheter
the dropdowns are closed or opened and fix this issue.
Closes #73
> #73 Fix inconsistent Sidebar/Top Navigation dropdown behavior 

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.5.0
Added Changelog for v1.6.0
Closes #108
- Docs change
> #108 v1.6.0 Changelog 

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
> Add 1.7.0 changelog

- libs/patterns/src/Login.tsx
> #134 - Fix logo condition in Login component

- libs/patterns/src/Login.tsx
* Module: Login
Add Changeable URL for "Forgotten Password" on Login pattern.
Closes #132 
> #132 - Changeable URL for "Forgotten Password" on Login pattern

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.6.0
Add v1.7.1 Changelog
Closes #140 
- Docs change
> #140 v1.7.1 Changelog

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.7.1
Release notes 1.7.2
Closes #144 
- Docs change
> #144 Release notes 1.7.2

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Add v1.7.4 Changelog
Closes #169 
- Docs change
> #169 v1.7.4 Changelog

- libs/form-elements/src/Toggle.tsx
- libs/theme/src/defaultTheme.tsx
* Module: form-elements, formik-elements
When disabled, the component has lowered opacity. The styles are defined inside tokens in order to allow changing if needed.
Closes #112 
> #112 - Improve disabled Toggle appearance

- libs/date/src/DateInput.tsx
- libs/date/src/DateRangeInput.tsx
- libs/date/src/DateTimeInput.tsx
- libs/date/src/TimeInput.tsx
- libs/selectors/src/Select.tsx
Fixed inconsistent focus when navigating through the following components:
- DateInput
- DateTimeInput
- DateRangeInput
- TimeInput
- Select
Closes #181 
> #181 Fix inconsistent focus for date inputs and select

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Add v1.8.0 Changelog
Closes #186 
- Docs change
> #186 - Changelog - v1.8.0

- libs/form-elements-advanced/src/RichTextEditor.tsx
- package.json
- storybook/src/form-elements-advanced/RichTextEditor.mdx
- storybook/src/form-elements-advanced/RichTextEditor.stories.tsx
- yarn.lock
1.8.0
* Module:
form-elements-advanced
I added `initialHtml` and `onHtmlChange` props to `RichTextEditor` component
#188 
- Docs change
- Dependency upgrade
> #188 Implement initialHtml and onHtmlChange props for RichTextEditor

- libs/form-elements/src/CheckboxGroup.tsx
- libs/form-elements/src/RadioGroup.tsx
- libs/formik-elements/src/CheckboxGroupField.tsx
- libs/formik-elements/src/RadioGroupField.tsx
* Module: formik-elements
Fix inconsistent error detection & premature validation error display for the following components:
-  CheckboxGroupField 
- RadioGroupField
Closes #184
> Fix CheckboxGroupField & RadioGroupField error handling

- yarn.lock
Ran `yarn install` locally so that the `yarn.lock` file updates according to the dependency bump in `package.json`
Closes #202 
> #202 Update yarn.lock

- .github/workflows/build.yml
Added a manual trigger for pipelines
Closes #206 
> #206 Add manual trigger for pipeline

- .github/workflows/build.yml
Added necessary file permission for the `actions/upload-pages-artifact@v1.0.4` to function propertly
Closes #209 
> #209 Fix Deploy to Github Pages

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Add v1.9.0 Changelog
Closes #214 
- Docs change
> #214 v1.9.0 Changelog

- libs/data-display/src/FileBrowser.tsx
- libs/data-display/src/index.tsx
- storybook/src/data-display/FileBrowser.mdx
- storybook/src/data-display/FileBrowser.stories.tsx
* Tiller version: 1.9.0
Added a new component `FileBrowser` which is used for displaying files in a similar manner to a file explorer on desktop.
Closes #216 
> #216 File Browser component

- libs/upload/src/DragZone.tsx
- libs/util/src/usePrevious.tsx
- storybook/src/formik-elements/DragZoneField.stories.tsx
- storybook/src/upload/DragZone.stories.tsx
1.9.0
* Module:
DragZoneField - DragZoneFieldLoader
Added preLoadDelay and postLoadDelay props to DragZone
[#220](https://github.com/croz-ltd/tiller/issues/220)
- Docs change
> #220 Add preLoadDelay and postLoadDelay props to DragZone

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.9.0
Add v1.9.0 Changelog
Closes #222 
- Docs change
> #222 v1.10.0 Changelog

- libs/alert/src/Modal.tsx
- storybook/src/alert/Modal.mdx
- storybook/src/alert/Modal.stories.tsx
1.10.0
* Module:
Alert
I added `dangerouslyBypassFocusLock` prop which solves problem when modul keeps focus, and elements in another popup cannot get it
#217 
- Docs change
> #217 Add dangerouslyBypassFocusLock prop on Modal which solves focus lock problems

- libs/date/src/DateInput.tsx
1.10.0
* Module:
Formik-elements - DateInputField
Now datepicker modal will close when tab is pressed when dateinput component is focused
#219 
> #219 Close dateinput's datepicker on tab key press

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.10.0
Add v1.11.0 Changelog
Closes #233 
- Docs change
> #233 v1.11.0 Changelog

- package.json
1.12.0
* Module:
project
Installed volta and pinned node@16.17.1 and yarn@3.0.0-rc.1 versions in package.json.
> Install volta and pin node and yarn versions

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Module:
- Breaking change (fix, enhancement or feature that would cause existing functionality to change in backward-incompatible way)
- Docs change
- Refactoring
- Dependency upgrade
> Add v1.13.0 release notes

- libs/form-elements/src/Input.tsx
- libs/selectors/src/Autocomplete.tsx
- libs/selectors/src/Select.tsx
- libs/selectors/src/TreeSelect.tsx
1.12.0
* Module:
form-elements, formik-elements
Removed clear button from input fields when they are disabled.
https://github.com/croz-ltd/tiller/issues/229
> #229 Remove clear button from input fields when they are disabled

- libs/data-display/src/DataTable.tsx
1.12.0
* Module:
data-display
Added new function for mapping DataTable children which fixes bug with sending multiple optional columns.
Added new function for mapping DataTable children which allows multiple optional columns to be send as children. That function is recursive function which is used for extracting children one by one if they are passed nested in arrays (as they are when we send multiple optional columns).
https://github.com/croz-ltd/tiller/issues/240
> #240 Add support for multiple optional columns in DataTable component

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
Add v1.14.0 Changelog
- Docs change
> v1.14.0 Changelog

- libs/menu/src/SidebarNavigation.tsx
* Tiller version: 1.15.0
* Module: menu
Fixed propagating visibleItemCount on SidebarNavigation
Closes #284 
> #284 Fixed propagating visibleItemCount on SidebarNavigation

- libs/menu/src/SidebarNavigation.tsx
- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.15.0
* Module: menu
Fixed propagating visibleItemCount on SidebarNavigation
Closes #284 
> Bugfix/284 Release notes

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.15.1
Add v1.16.0 Changelog
- Docs change
> v1.16.0 Changelog

- libs/core/src/Tooltip.tsx
- libs/theme/src/defaultTheme.tsx
- storybook/src/core/Tooltip.stories.tsx
* Tiller version: 1.16.0
* Module: core
Added a new `color` prop (dark/light) to `Tooltip` (defaults to dark). Adjusted font in the tooltip popup. Adjusted tokens to match new customization.
#297
- Breaking change in tokens configuration (fix, enhancement or feature that would cause existing functionality to change in backward-incompatible way)
> #297 Adjust `Tooltip` font and add `light` theme

- storybook/src/base-documentation/ReleaseNotes.stories.mdx
* Tiller version: 1.17.0
Add v1.18.0 Changelog
- Docs change
> v1.18.0 Changelog
